from __future__ import annotations

from decimal import Decimal


AGENT_LIFECYCLE_BASELINE_MONTH = "2025-01"
CAMPAIGN_RANKING_LIMIT = 8
PROMOTION_DISCOUNT_RATE = Decimal("0.20")

INCENTIVE_FULL_ACHIEVEMENT_RATIO = 1.0
INCENTIVE_HALF_ACHIEVEMENT_RATIO = 0.9
INCENTIVE_FULL_MULTIPLIER = 1.0
INCENTIVE_HALF_MULTIPLIER = 0.5
INCENTIVE_ZERO_MULTIPLIER = 0.0
