import { Building2, CalendarRange, PieChart as PieChartIcon, Users } from 'lucide-react';
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

import { Metric } from '../../components/common/DataDisplay';
import { formatAmount, formatInt, formatPercent } from '../../lib/formatters';
import { BreakdownTable } from './BreakdownTable';
import type { CurrentDashboardProps } from './CurrentDashboard';
import {
  CompactCurrency, CompactPieSection, DeltaCard, KpiPerformanceCard, PeriodTable,
  formatCompactDonutValue, formatCompactAxisValue, getBon2AccTone, getFocusTone, sumChartValues,
} from './DashboardWidgets';

function CurrentSummary<R extends string, S extends string, A extends string>({ model }: { model: CurrentDashboardProps<R, S, A> }) {
  const summary = model.summary;
  return <div data-testid="hub-overview-card" className="glass min-w-0 space-y-3 rounded-3xl p-4">
    <div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="truncate text-sm font-bold">Overview — {model.currentMonth}</h3><p className="mt-0.5 text-[11px] leading-relaxed text-slate-500">{model.statusLabel}</p></div><span className="shrink-0 rounded-xl bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{summary.last_sale_date ?? '-'}</span></div>
    <div data-testid="hub-overview-layout" className="grid min-w-0 items-start gap-3 min-[1500px]:grid-cols-[minmax(0,2fr)_minmax(520px,1.5fr)]">
      <div data-testid="hub-summary-panel" className="min-w-0 space-y-3">
        <div className="min-w-0 rounded-2xl bg-slate-50 p-3 dark:bg-slate-800/50"><div className="mb-3 grid grid-cols-3 gap-2 text-center">
          <div><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-600 dark:text-slate-300">Target</div><div className="mt-0.5 text-[13px] font-bold text-slate-600 dark:text-slate-300"><CompactCurrency value={Number(summary.total_target)} /></div></div>
          <div><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-600 dark:text-slate-300">Realizat</div><div className="mt-0.5 text-[13px] font-bold text-slate-800 dark:text-slate-100"><CompactCurrency value={Number(summary.total_sales)} /></div></div>
          <div><div className="text-[10px] font-semibold uppercase tracking-wide text-indigo-700 dark:text-indigo-300">Previziune</div><div className="mt-0.5 text-[13px] font-bold text-indigo-600 dark:text-indigo-400"><CompactCurrency value={Number(summary.forecast_sales ?? summary.total_sales)} /></div></div>
        </div><div className="relative h-3 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700"><div className="absolute inset-y-0 left-0 rounded-full bg-indigo-200 dark:bg-indigo-700" style={{ width: `${Math.min(Number(summary.forecast_target_progress_pct ?? 0), 100)}%` }} /><div className="absolute inset-y-0 left-0 rounded-full bg-indigo-600" style={{ width: `${Math.min(Number(summary.target_progress_pct ?? 0), 100)}%` }} /></div><div className="mt-1.5 flex justify-between text-[10px] font-semibold"><span className="text-indigo-600">Actual {formatPercent(summary.target_progress_pct)}</span><span className="text-slate-600 dark:text-slate-300">Forecast {formatPercent(summary.forecast_target_progress_pct)}</span></div></div>
        <div className="grid min-w-0 gap-2 [grid-template-columns:repeat(auto-fit,minmax(min(100%,78px),1fr))]"><Metric label="Bonuri" value={formatInt(summary.total_receipts)} compact /><Metric label="Accesorii nete" value={formatInt(summary.total_quantity)} compact /><Metric label="Magazine / Agenți" value={<span className="flex items-baseline gap-1 sm:gap-1.5"><span>{formatInt(summary.total_stores)}</span><span className="text-slate-300 dark:text-slate-600">/</span><span>{formatInt(summary.total_agents)}</span></span>} compact /><Metric label="Zile lucrate" value={formatInt(summary.working_days)} compact /><Metric label="Med. zilnica" value={formatAmount(summary.daily_average ?? 0)} compact /><Metric label="Medie produs" value={formatAmount(summary.medie_produs ?? 0)} compact /><Metric label="Val. medie bon" value={formatAmount(summary.total_receipts > 0 ? Number(summary.total_sales) / Number(summary.total_receipts) : 0)} compact /><Metric label="Cartele" value={formatInt(summary.cartele_qty ?? 0)} compact /></div>
      </div>
      <div data-testid="hub-donut-grid" className="grid min-w-0 items-start gap-2.5 xl:grid-cols-2"><KpiPerformanceCard title="Bonuri cu accesorii" value={summary.proc_bon2acc} tone={getBon2AccTone(Number(summary.proc_bon2acc ?? 0))} chartData={model.receiptBucketChartData} dataKey="receipt_count" nameKey="bucket" formatValue={formatInt} /><KpiPerformanceCard title="Pondere produse Focus" value={summary.prc_focus_acc_qty} tone={getFocusTone(Number(summary.prc_focus_acc_qty ?? 0))} chartData={model.focusSubcategoryChartData} dataKey="quantity_total" nameKey="category" formatValue={formatInt} /></div>
    </div>
  </div>;
}

function CurrentComparison<R extends string, S extends string, A extends string>({ model }: { model: CurrentDashboardProps<R, S, A> }) {
  const deltas = model.comparisonDeltas;
  return <div data-testid="hub-period-comparison-layout" className="grid min-w-0 items-stretch gap-3 min-[1500px]:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]">
    <div data-testid="hub-period-comparison-card" className="glass flex min-w-0 flex-col overflow-hidden rounded-3xl p-4"><div className="mb-3 flex items-center gap-2"><CalendarRange size={16} className="text-indigo-500" /><h3 className="text-sm font-bold">Comparatie perioade</h3></div>{!model.periodComparison || !deltas ? <div className="text-xs text-slate-500">Date indisponibile pentru comparatia de perioade.</div> : <div className="min-w-0 flex-1"><PeriodTable current={model.periodComparison.current} previous={model.periodComparison.previous} yoy={model.periodComparison.year_over_year} /></div>}</div>
    <div data-testid="hub-period-kpi-card" className="glass flex min-w-0 flex-col overflow-hidden rounded-3xl p-4"><div className="mb-3 flex items-center gap-2"><CalendarRange size={16} className="text-indigo-500" /><h3 className="text-sm font-bold">Variatii fata de perioade</h3></div>{!deltas ? <div className="text-xs text-slate-500">Date indisponibile pentru variatiile de perioada.</div> : <div className="grid min-w-0 flex-1 grid-cols-2 gap-3 min-[1500px]:grid-cols-1 min-[1500px]:grid-rows-2"><DeltaCard title="Vs luna trecuta" compact salesDelta={deltas.previousSales} salesPct={deltas.previousSalesPct} receiptsDelta={deltas.previousReceipts} receiptsPct={deltas.previousReceiptsPct} quantityDelta={deltas.previousQuantity} quantityPct={deltas.previousQuantityPct} /><DeltaCard title="Vs anul trecut" compact salesDelta={deltas.yearSales} salesPct={deltas.yearSalesPct} receiptsDelta={deltas.yearReceipts} receiptsPct={deltas.yearReceiptsPct} quantityDelta={deltas.yearQuantity} quantityPct={deltas.yearQuantityPct} /></div>}</div>
  </div>;
}

function CurrentCharts<R extends string, S extends string, A extends string>({ model }: { model: CurrentDashboardProps<R, S, A> }) {
  return <div data-testid="hub-chart-layout" className="grid min-w-0 items-stretch gap-3 min-[1500px]:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]">
    <div className="glass flex min-w-0 flex-col rounded-3xl p-3 sm:p-4"><div className="mb-2 flex items-center gap-2 sm:mb-3"><CalendarRange size={16} className="text-indigo-500" /><h3 className="text-sm font-bold">Evolutie zilnica pentru {model.currentMonth}</h3></div><div className="-mx-2 aspect-[16/6] min-h-56 max-h-72 w-auto rounded-xl bg-slate-50/80 p-0.5 sm:mx-0 sm:w-full sm:rounded-2xl sm:p-2 dark:bg-slate-800/40 min-[1500px]:aspect-auto min-[1500px]:min-h-[24rem] min-[1500px]:max-h-none min-[1500px]:flex-1"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}><ComposedChart data={model.dailyChartData} margin={{ top: 4, right: 0, bottom: 0, left: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={0.15} /><XAxis dataKey="day" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis yAxisId="sales" width={38} tick={{ fontSize: 10 }} tickFormatter={formatCompactAxisValue} axisLine={false} tickLine={false} /><Tooltip formatter={(value: unknown) => formatAmount(Number(value))} /><Legend /><Bar yAxisId="sales" dataKey="sales" name="Vanzari" fill="#4f46e5" radius={[8, 8, 0, 0]} /><Line yAxisId="sales" type="monotone" dataKey="sales_last_year" name="Anul trecut" stroke="#10b981" strokeWidth={2} strokeDasharray="5 3" dot={false} connectNulls /><Line yAxisId="sales" type="monotone" dataKey="sales_forecast" name="Prognoza" stroke="#f59e0b" strokeWidth={2} strokeDasharray="3 3" dot={false} connectNulls /></ComposedChart></ResponsiveContainer></div></div>
    <div className="glass flex min-w-0 flex-col rounded-3xl p-3 sm:p-4"><div className="mb-2 flex items-center gap-2 sm:mb-3"><PieChartIcon size={16} className="text-indigo-500" /><h3 className="text-sm font-bold">Top categorii si branduri</h3></div><div className="grid min-w-0 flex-1 gap-2 min-[1500px]:grid-rows-2"><CompactPieSection title="Top categorii" emptyLabel="Nu exista categorii disponibile pentru filtrarea curenta." pieData={model.categoryMixChartData} dataKey="sales_total" nameKey="category" valueFormatter={formatAmount} centerValue={formatCompactDonutValue(sumChartValues(model.categoryMixChartData, 'sales_total'))} compact /><CompactPieSection title="Branduri compatibile" emptyLabel="Nu exista date pentru brandurile urmarite." pieData={model.brandMixChartData} dataKey="sales_total" nameKey="brand" valueFormatter={formatAmount} centerValue={formatCompactDonutValue(sumChartValues(model.brandMixChartData, 'sales_total'))} compact /></div></div>
  </div>;
}

function CurrentBreakdowns<R extends string, S extends string, A extends string>({ model }: { model: CurrentDashboardProps<R, S, A> }) {
  return <div className="space-y-3">
    <div className="min-w-0"><BreakdownTable title="RM — Regional Manager" icon={<Users size={16} className="text-indigo-500" />} subtitle={`Filtrare: ${model.filterScopeLabel} · Sortare: ${model.regionalColumns.find((column) => column.key === model.regionalSort.key)?.label} (${model.regionalSort.direction}) · ${model.regionals.length} regionale`} rows={model.sortedRegionals} columns={model.regionalColumns} sortKey={model.regionalSort.key} sortDirection={model.regionalSort.direction} onSort={model.onSortRegionals} rowKey={(row) => row.regional} exportFilename={`hub_${model.currentMonth}_rm`} exportSheetName={`RM ${model.currentMonth}`} exportColumns={[
      { header: 'Regional', value: (row) => row.regional }, { header: 'Target', value: (row) => row.target, format: 'currency' }, { header: 'Vanzari', value: (row) => row.total_vanzari, format: 'currency' }, { header: 'Procent', value: (row) => row.proc_realizare_target, format: 'percentPoints' }, { header: 'Forecast%', value: (row) => row.forecast_target_pct, format: 'percentPoints' }, { header: 'Promo buc.', value: (row) => row.promo_qty, format: 'integer' }, { header: 'Discount promo', value: (row) => row.promo_discount_value, format: 'currency' }, { header: 'Cantitate', value: (row) => row.qty_total, format: 'integer' }, { header: 'Medie produs', value: (row) => row.medie_produs, format: 'currency' }, { header: 'Nr bonuri', value: (row) => row.nr_bonuri, format: 'integer' }, { header: 'ProcBon2Acc', value: (row) => row.proc_bon2acc, format: 'percentPoints' }, { header: 'Focus%', value: (row) => row.prc_focus_acc_qty, format: 'percentPoints' },
    ]} /></div>
    <div className="min-w-0"><BreakdownTable title="Magazine" icon={<Building2 size={16} className="text-indigo-500" />} subtitle={`Filtrare: ${model.filterScopeLabel} · Sortare: ${model.storeColumns.find((column) => column.key === model.storeSort.key)?.label} (${model.storeSort.direction}) · ${model.stores.length} magazine`} rows={model.sortedStores} columns={model.storeColumns} sortKey={model.storeSort.key} sortDirection={model.storeSort.direction} onSort={model.onSortStores} rowKey={(row) => row.site_code} exportFilename={`hub_${model.currentMonth}_magazine`} exportSheetName={`Magazine ${model.currentMonth}`} exportColumns={[
      { header: 'Firma', value: (row) => row.firma }, { header: 'Magazin', value: (row) => row.locatie }, { header: 'Target', value: (row) => row.target, format: 'currency' }, { header: 'Vanzari', value: (row) => row.total_vanzari, format: 'currency' }, { header: 'Procent', value: (row) => row.proc_realizare_target, format: 'percentPoints' }, { header: 'Forecast%', value: (row) => row.forecast_target_pct, format: 'percentPoints' }, { header: 'Promo buc.', value: (row) => row.promo_qty, format: 'integer' }, { header: 'Discount promo', value: (row) => row.promo_discount_value, format: 'currency' }, { header: 'Cantitate', value: (row) => row.qty_total, format: 'integer' }, { header: 'Medie produs', value: (row) => row.medie_produs, format: 'currency' }, { header: 'Nr bonuri', value: (row) => row.nr_bonuri, format: 'integer' }, { header: 'ProcBon2Acc', value: (row) => row.proc_bon2acc, format: 'percentPoints' }, { header: 'Focus%', value: (row) => row.prc_focus_acc_qty, format: 'percentPoints' }, { header: 'Retururi', value: (row) => row.return_receipt_count, format: 'integer' }, { header: 'Agenti', value: (row) => row.nr_agenti, format: 'integer' }, { header: 'Zile active', value: (row) => row.zile_active, format: 'integer' },
    ]} /></div>
    <BreakdownTable title="Agenti - Toti agentii" subtitle={`Filtrare: ${model.filterScopeLabel} · Sortare: ${model.agentColumns.find((column) => column.key === model.agentSort.key)?.label} (${model.agentSort.direction}) · ${model.agents.length} agenti`} rows={model.sortedAgents} columns={model.agentColumns} sortKey={model.agentSort.key} sortDirection={model.agentSort.direction} onSort={model.onSortAgents} rowKey={(row) => `${row.agent}-${row.site_code}`} exportFilename={`hub_${model.currentMonth}_agenti`} exportSheetName={`Agenti ${model.currentMonth}`} exportColumns={[
      { header: 'Agent', value: (row) => row.agent }, { header: 'Firma', value: (row) => row.firma }, { header: 'Magazin', value: (row) => row.locatie }, { header: 'Target', value: (row) => row.target, format: 'currency' }, { header: 'Vanzari', value: (row) => row.total_vanzari, format: 'currency' }, { header: 'Procent', value: (row) => row.proc_realizare_target, format: 'percentPoints' }, { header: 'Promo buc.', value: (row) => row.promo_qty, format: 'integer' }, { header: 'Discount promo', value: (row) => row.promo_discount_value, format: 'currency' }, { header: 'Cantitate', value: (row) => row.acc_qty_realizat, format: 'integer' }, { header: 'Medie produs', value: (row) => row.medie_produs, format: 'currency' }, { header: 'Nr bonuri', value: (row) => row.nr_bonuri, format: 'integer' }, { header: 'ProcBon2Acc', value: (row) => row.proc_bon2acc, format: 'percentPoints' }, { header: 'Focus%', value: (row) => row.prc_focus_acc_qty, format: 'percentPoints' }, { header: 'Retururi', value: (row) => row.return_receipt_count, format: 'integer' }, { header: 'Zile lucrate', value: (row) => row.zile_lucrate, format: 'integer' }, { header: 'Medie zilnica', value: (row) => row.medie_zilnica, format: 'currency' },
    ]} />
  </div>;
}

export function CurrentOverview<R extends string, S extends string, A extends string>({ model }: { model: CurrentDashboardProps<R, S, A> }) {
  return <><CurrentSummary model={model} /><CurrentComparison model={model} /><CurrentCharts model={model} /><CurrentBreakdowns model={model} /></>;
}
