import { AlertTriangle, BadgeDollarSign, Building2, ChartNoAxesCombined, TrendingDown, TrendingUp } from 'lucide-react';
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

import type { PnlAnnualPoint, PnlMonthlyPoint } from '../../api/storePnl';
import { TableHeaderCell } from '../../components/common/TableHeader';
import { CATEGORY_LABELS, compactMoney, marginPct, money, monthLabel, pnlStoreOptionValue } from './model';
import type { PnlController } from './usePnlController';

function FinancialMetric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof TrendingUp }) {
  const positive = value >= 0;
  return <div className="min-w-0 p-4 sm:p-5"><div className="flex items-center justify-between text-xs font-medium uppercase tracking-wide text-slate-500">{label}<span className="rounded-xl bg-indigo-50 p-2 text-indigo-600 dark:bg-indigo-950/40"><Icon size={16} /></span></div><div className={`mt-3 text-xl font-bold ${label.includes('EBIT') ? (positive ? 'text-emerald-600' : 'text-rose-600') : 'text-slate-900 dark:text-slate-100'}`}>{money.format(value)}</div></div>;
}

export function PnlFilters({ model }: { model: PnlController }) {
  const { monthsQuery, regionsQuery, storesQuery } = model;
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900 sm:p-5">
      <div><div className="flex items-center gap-2"><BadgeDollarSign className="text-indigo-600" /><h2 className="text-xl font-bold text-slate-900 dark:text-white">Profit &amp; Loss</h2></div><p className="mt-1 text-sm text-slate-500">Performanță financiară pe rețea, regiune, companie și magazin.</p></div>
      <div className="mt-4 grid grid-cols-2 gap-2 lg:mt-3 lg:grid-cols-5">
        <MonthSelect label="De la" value={model.startMonth} months={monthsQuery.data ?? []} onChange={model.setStartMonth} />
        <MonthSelect label="Până la" value={model.endMonth} months={monthsQuery.data ?? []} onChange={model.setEndMonth} />
        <label className="text-xs text-slate-500">Companie<select value={model.company} onChange={(event) => model.selectCompany(event.target.value)} className="mt-1 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="">Toată rețeaua</option><option value="Mobiup">Mobiup</option><option value="Mobicell">Mobicell</option></select></label>
        <label className="text-xs text-slate-500">RM / regiune<select value={model.regional} onChange={(event) => model.selectRegional(event.target.value)} disabled={regionsQuery.isLoading || regionsQuery.isError} className="mt-1 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm disabled:opacity-60 dark:border-slate-700 dark:bg-slate-900"><option value="">Toate regiunile</option>{regionsQuery.data?.map((region) => <option key={region} value={region}>{region}</option>)}</select></label>
        <label className="col-span-2 text-xs text-slate-500 lg:col-span-1">Magazin<select value={model.storeScope} onChange={(event) => model.setStoreScope(event.target.value)} disabled={storesQuery.isLoading || storesQuery.isError} className="mt-1 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm disabled:opacity-60 dark:border-slate-700 dark:bg-slate-900"><option value="">{storesQuery.isError ? 'Magazine indisponibile' : 'Toate magazinele'}</option>{storesQuery.data?.map((store) => <option key={`${store.company_name}-${store.site_code}`} value={pnlStoreOptionValue(store)}>{store.location} · {store.site_code}{store.scope_company ? ` · ${store.scope_company}` : ''}</option>)}</select></label>
      </div>
    </div>
  );
}

function MonthSelect({ label, value, months, onChange }: { label: string; value: string; months: Array<{ month: string; has_estimated: boolean }>; onChange: (value: string) => void }) {
  return <label className="text-xs text-slate-500">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900">{months.map((item) => <option key={item.month} value={item.month}>{monthLabel(item.month)}{item.has_estimated ? ' · estimat' : ''}</option>)}</select></label>;
}

export function PnlNotices({ model }: { model: PnlController }) {
  const { data, reconciliationWarnings } = model;
  return <>{data?.monthly.some((point) => point.is_estimated) && <div className="flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-300"><AlertTriangle size={17} className="mt-0.5 shrink-0" /><span>Intervalul conține luni estimate. Acestea sunt marcate distinct în grafic și în tabel.</span></div>}{reconciliationWarnings.length > 0 && <div className="flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-300"><AlertTriangle size={17} className="mt-0.5 shrink-0" /><div><strong>Reconciliere de verificat</strong><p className="mt-1 text-xs">{reconciliationWarnings.map((item) => `${monthLabel(item.month)}: diferență ${money.format(item.difference_to_net)}`).join(' · ')}</p></div></div>}</>;
}

function FinancialSummary({ model }: { model: PnlController }) {
  const data = model.data!;
  const reconciliation = model.singleReconciliation;
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="grid divide-y divide-slate-200 sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-5 dark:divide-slate-700"><FinancialMetric label="Venituri" value={data.summary.revenue} icon={TrendingUp} /><FinancialMetric label="Marjă brută" value={data.summary.gross_margin} icon={ChartNoAxesCombined} /><FinancialMetric label="Costuri operaționale" value={data.summary.operating_costs} icon={TrendingDown} /><FinancialMetric label="EBITDA" value={data.summary.ebitda} icon={BadgeDollarSign} /><FinancialMetric label={`EBIT · ${marginPct(data.summary)}`} value={data.summary.ebit} icon={Building2} /></div>
    {reconciliation?.pnl_to_net_sales_pct !== null && reconciliation && <div className="border-t border-slate-200 px-4 py-2 text-xs text-slate-500 dark:border-slate-700">Vânzări Retail fără TVA: {money.format(reconciliation.retail_sales_net)} · Venit P&amp;L / vânzări nete: {reconciliation.pnl_to_net_sales_pct?.toFixed(1)}%</div>}
    {model.variance && <div className="grid grid-cols-3 gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3 text-xs dark:border-slate-700 dark:bg-slate-800/50">{[['Venituri', model.variance.revenuePct], ['EBITDA', model.variance.ebitdaPct], ['EBIT', model.variance.ebitPct]].map(([label, raw]) => { const value = raw as number | null; return <div key={label as string}><span className="text-slate-500">{label as string} vs {monthLabel(model.variance!.previousMonth)}</span><strong className={`ml-2 tabular-nums ${value === null ? 'text-slate-400' : value >= 0 ? 'text-emerald-600' : 'text-rose-600'}`}>{value === null ? '—' : `${value > 0 ? '+' : ''}${value.toFixed(1)}%`}</strong></div>; })}</div>}
  </div>;
}

function MonthlyChart({ model }: { model: PnlController }) {
  const points = model.data!.monthly;
  return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold text-slate-900 dark:text-white">Evoluție lunară</h3><div className="flex items-center gap-3 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><span className="h-2.5 w-2.5 rounded-full bg-indigo-600" /> Date efective</span><span className="inline-flex items-center gap-1"><span className="h-2.5 w-2.5 rounded-full bg-amber-500" /> Date estimate</span></div></div><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={points}><CartesianGrid strokeDasharray="3 3" stroke="#94a3b833" /><XAxis dataKey="month" tickFormatter={monthLabel} fontSize={11} /><YAxis tickFormatter={(value) => compactMoney.format(value)} fontSize={11} /><Tooltip formatter={(value) => money.format(Number(value))} labelFormatter={(label) => `${monthLabel(String(label))}${points.find((point) => point.month === label)?.is_estimated ? ' · estimat' : ''}`} /><Legend /><Line type="monotone" dataKey="revenue" name="Venituri" stroke="#4f46e5" strokeWidth={2.5} dot={({ cx, cy, payload }: { cx?: number; cy?: number; payload: PnlMonthlyPoint }) => <circle cx={cx} cy={cy} r={payload.is_estimated ? 5 : 3} fill={payload.is_estimated ? '#f59e0b' : '#4f46e5'} />} /><Line type="monotone" dataKey="ebit" name="EBIT" stroke="#f43f5e" strokeWidth={3} strokeDasharray="8 6" dot={{ r: 2, fill: '#f43f5e' }} /><Line type="monotone" dataKey="ebitda" name="EBITDA" stroke="#10b981" strokeWidth={2.5} dot={{ r: 4, fill: '#10b981', stroke: '#ffffff', strokeWidth: 1.5 }} /></LineChart></ResponsiveContainer></div></div>;
}

function AnnualChart({ model }: { model: PnlController }) {
  const query = model.annualQuery;
  return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900 dark:text-white">Evoluție anuală</h3><p className="text-xs text-slate-500">Total pentru lunile disponibile din fiecare an; punctele portocalii includ estimări.</p></div>{query.isLoading && <span className="text-xs text-slate-500">Se încarcă…</span>}</div>{query.isError ? <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">Nu am putut încărca evoluția anuală.</div> : query.data?.length ? <div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={query.data}><CartesianGrid strokeDasharray="3 3" stroke="#94a3b833" /><XAxis dataKey="year" fontSize={11} /><YAxis tickFormatter={(value) => compactMoney.format(value)} fontSize={11} /><Tooltip formatter={(value) => money.format(Number(value))} labelFormatter={(label, payload) => { const point = payload?.[0]?.payload as PnlAnnualPoint | undefined; return `Anul ${String(label)}${point ? ` · ${point.store_count} magazine · ${point.month_count} luni` : ''}`; }} /><Legend /><Line type="monotone" dataKey="revenue" name="Venituri" stroke="#4f46e5" strokeWidth={2.5} dot={({ cx, cy, payload }: { cx?: number; cy?: number; payload: PnlAnnualPoint }) => <circle cx={cx} cy={cy} r={payload.is_estimated ? 6 : 4} fill={payload.is_estimated ? '#f59e0b' : '#4f46e5'} />} /><Line type="monotone" dataKey="ebit" name="EBIT" stroke="#f43f5e" strokeWidth={3} strokeDasharray="8 6" dot={{ r: 2, fill: '#f43f5e' }} /><Line type="monotone" dataKey="ebitda" name="EBITDA" stroke="#10b981" strokeWidth={2.5} dot={{ r: 4, fill: '#10b981', stroke: '#ffffff', strokeWidth: 1.5 }} /></LineChart></ResponsiveContainer></div> : !query.isLoading && <div className="py-12 text-center text-sm text-slate-500">Nu există istoric anual pentru selecția curentă.</div>}</div>;
}

function CategoryBreakdown({ model }: { model: PnlController }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 className="mb-3 font-semibold">Structură P&amp;L</h3><div className="space-y-2">{Object.entries(model.data!.categories).map(([code, value]) => <div key={code} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm dark:bg-slate-800/60"><span className="text-slate-600 dark:text-slate-300">{CATEGORY_LABELS[code] ?? code}</span><span className="font-semibold tabular-nums">{money.format(value)}</span></div>)}</div></div>;
}

function StoreCard({ store }: { store: PnlController['filteredStores'][number] }) {
  return <article className="rounded-2xl border border-slate-200 bg-slate-50/70 p-3 dark:border-slate-700 dark:bg-slate-800/40"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{store.location}</p><p className="truncate text-[11px] text-slate-500">{store.company} · {store.site_code}</p></div><div className={`shrink-0 text-right text-sm font-black tabular-nums ${store.ebit < 0 ? 'text-rose-600' : 'text-emerald-600'}`}>{money.format(store.ebit)}<p className="text-[10px] font-medium text-slate-400">EBIT</p></div></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><p className="text-[10px] text-slate-400">Venituri</p><p className="font-bold tabular-nums">{money.format(store.revenue)}</p></div><div className="text-right"><p className="text-[10px] text-slate-400">EBITDA</p><p className={store.ebitda < 0 ? 'font-bold text-rose-600' : 'font-bold'}>{money.format(store.ebitda)}</p></div></div></article>;
}

function StoresPanel({ model }: { model: PnlController }) {
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between gap-3 border-b border-slate-200 p-4 dark:border-slate-700"><div><h3 className="font-semibold">Magazine</h3><p className="text-xs text-slate-500">ordonate după EBIT</p></div><input value={model.storeSearch} onChange={(event) => model.setStoreSearch(event.target.value)} placeholder="Caută magazin…" className="w-44 rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-slate-700" /></div><div className="space-y-2 p-3 lg:hidden">{model.filteredStores.map((store) => <StoreCard key={`${store.company}-${store.source_site_code}:mobile`} store={store} />)}</div><div className="hidden max-h-[580px] overflow-auto lg:block"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-slate-500 dark:bg-slate-800"><tr><TableHeaderCell>Magazin</TableHeaderCell><TableHeaderCell align="right">Venituri</TableHeaderCell><TableHeaderCell align="right">EBITDA</TableHeaderCell><TableHeaderCell align="right">EBIT</TableHeaderCell></tr></thead><tbody>{model.filteredStores.map((store) => <tr key={`${store.company}-${store.source_site_code}`} className="border-t border-slate-100 dark:border-slate-800"><td className="px-3 py-2"><div className="font-medium">{store.location}</div><div className="text-xs text-slate-500">{store.company} · {store.site_code}{store.has_estimates && <span className="ml-1 rounded bg-amber-100 px-1.5 py-0.5 text-amber-700">estimat</span>}</div></td><td className="px-3 py-2 text-right tabular-nums">{money.format(store.revenue)}</td><td className={`px-3 py-2 text-right tabular-nums ${store.ebitda < 0 ? 'text-rose-600' : ''}`}>{money.format(store.ebitda)}</td><td className={`px-3 py-2 text-right font-semibold tabular-nums ${store.ebit < 0 ? 'text-rose-600' : 'text-emerald-600'}`}>{money.format(store.ebit)}</td></tr>)}</tbody></table></div></div>;
}

export function PnlDataView({ model }: { model: PnlController }) {
  return <><FinancialSummary model={model} /><div className="grid gap-4 xl:grid-cols-[7fr_5fr] xl:items-stretch"><MonthlyChart model={model} /><AnnualChart model={model} /></div><div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><CategoryBreakdown model={model} /><StoresPanel model={model} /></div></>;
}
