// @vitest-environment jsdom
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { ApiError } from '../../api/client';
const api = vi.hoisted(() => ({ saveStoreHours: vi.fn(), downloadAttendance: vi.fn(), readCalendar: vi.fn(), calendarStores: vi.fn(), calendarCandidates: vi.fn(), confirmCalendarAgent: vi.fn(), saveCalendarDays: vi.fn() }));
const auth = vi.hoisted(() => ({ profile: { groups: ['unihub-manager'] } }));
vi.mock('../../api/grileCalendar', () => api);
vi.mock('../../auth/AuthContext', () => ({ useAuth: () => ({ user: auth }) }));
import { NativeCalendar } from './NativeCalendar';
const store = { site_code: 'S1', locatie: 'Magazin Alpha', regional: 'Manager R', firma: 'Firm', asm: '' };
const roster = [{ month: '2026-09', agent_code: 'AG1', home_site_code: 'S1', active: true, revision: 1 }];
const day = { agent_code: 'AG1', work_date: '2026-09-01', site_code: 'S1', status: 'work', supplemental: false, revision: 1 };
beforeEach(() => {
  vi.resetAllMocks();
  auth.profile.groups = ['unihub-manager'];
  HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  HTMLDialogElement.prototype.close = function () { this.open = false; };
  api.calendarStores.mockResolvedValue([store]);
  api.calendarCandidates.mockResolvedValue([{ agent_code: 'AG2', site_codes: ['S1'], needs_active_confirmation: true }]);
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster, days: [day], attendance: [] });
});
afterEach(cleanup);
function mount() { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })}><NativeCalendar initialMonth="2026-09" /></QueryClientProvider>); }
async function openStore() { await userEvent.click(await screen.findByRole('button', { name: /Magazin Alpha/ })); }
it('exposes TL management in a month with no confirmed Team Leaders', async () => {
  mount();
  expect(await screen.findByRole('button', { name: 'TL · Grile Team Leaders' })).toBeInTheDocument();
});
it('opens grouped store, shows attendance, and reopens calendar', async () => {
  mount(); await openStore();
  expect(screen.getByRole('dialog')).toHaveAccessibleName('Magazin Alpha');
  await userEvent.click(screen.getByRole('tab', { name: 'Pontaj' }));
  expect(screen.getByRole('table')).toHaveTextContent('AG1');
  await userEvent.click(screen.getByLabelText('Închide magazinul'));
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  await openStore();
  expect(screen.getByRole('button', { name: 'Editează 2026-09-01' })).toBeInTheDocument();
});
it('saves leave and reloads the shared calendar', async () => {
  mount(); await openStore();
  await userEvent.click(screen.getByRole('button', { name: 'Editează 2026-09-01' }));
  await userEvent.selectOptions(screen.getByLabelText('Tip zi'), 'leave');
  api.saveCalendarDays.mockResolvedValue([]);
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster, days: [{ ...day, status: 'leave', revision: 2 }], attendance: [] });
  await userEvent.click(screen.getByRole('button', { name: 'Salvează ziua' }));
  await waitFor(() => expect(api.saveCalendarDays).toHaveBeenCalledWith('2026-09', [expect.objectContaining({ agent_code: 'AG1', status: 'leave', expected_revision: 1 })]));
  await waitFor(() => expect(screen.queryByRole('button', { name: 'Salvează ziua' })).not.toBeInTheDocument());
  expect(screen.getByRole('button', { name: 'Editează 2026-09-01' })).toHaveTextContent('Concediu');
});
it('requires explicit reload after a conflict', async () => {
  mount(); await openStore();
  await userEvent.click(screen.getByRole('button', { name: 'Editează 2026-09-01' }));
  api.saveCalendarDays.mockRejectedValue(new ApiError(409, 'stale', null));
  await userEvent.click(screen.getByRole('button', { name: 'Salvează ziua' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('Programul s-a schimbat');
  expect(screen.getByRole('button', { name: 'Salvează ziua' })).toBeDisabled();
  await userEvent.click(screen.getByRole('button', { name: 'Reîncarcă programul' }));
  await waitFor(() => expect(screen.queryByRole('alert')).not.toBeInTheDocument());
});
it('confirms a candidate explicitly at the selected home store', async () => {
  mount(); await openStore();
  await userEvent.click(screen.getByText('Confirmă agenții și magazinul de bază'));
  await userEvent.selectOptions(screen.getByLabelText('Cod agent pentru confirmare'), 'AG2');
  api.confirmCalendarAgent.mockResolvedValue({});
  await userEvent.click(screen.getByRole('button', { name: 'Confirmă în Magazin Alpha' }));
  await waitFor(() => expect(api.confirmCalendarAgent).toHaveBeenCalledWith('2026-09', 'AG2', { home_site_code: 'S1', active: true, expected_revision: 0 }));
});
it('blocks agents and keeps HR read-only', async () => {
  auth.profile.groups = ['unihub-agent'];
  const view = mount();
  expect(screen.getByText(/echipei de management/)).toBeInTheDocument();
  expect(api.readCalendar).not.toHaveBeenCalled();
  view.unmount(); auth.profile.groups = ['unihub-hr']; mount(); await openStore();
  expect(screen.getByText('Mod consultare.')).toBeInTheDocument();
  expect(api.calendarCandidates).not.toHaveBeenCalled();
});
it('does not turn a failed month load into an empty editable schedule', async () => {
  api.readCalendar.mockRejectedValue(new Error('offline'));
  mount();
  expect(await screen.findByRole('alert')).toHaveTextContent('nu poate fi încărcat');
  expect(screen.queryByRole('button', { name: /Magazin Alpha/ })).not.toBeInTheDocument();
});
it('corrects an existing home store using the selected roster revision', async () => {
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster: [{ ...roster[0], home_site_code: 'S2', revision: 4 }], days: [], attendance: [] });
  mount(); await openStore();
  await userEvent.click(screen.getByText('Confirmă agenții și magazinul de bază'));
  await userEvent.selectOptions(screen.getByLabelText('Cod agent pentru confirmare'), 'AG1');
  api.confirmCalendarAgent.mockResolvedValue({});
  await userEvent.click(screen.getByRole('button', { name: 'Confirmă în Magazin Alpha' }));
  await waitFor(() => expect(api.confirmCalendarAgent).toHaveBeenCalledWith('2026-09', 'AG1', { home_site_code: 'S1', active: true, expected_revision: 4 }));
});
it('deactivates and reactivates confirmed agents through revision-fenced updates', async () => {
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster, days: [], attendance: [] });
  mount(); await openStore();
  await userEvent.click(screen.getByText('Confirmă agenții și magazinul de bază'));
  await userEvent.selectOptions(screen.getByLabelText('Cod agent pentru confirmare'), 'AG1');
  await userEvent.click(screen.getByLabelText('Activ în această lună'));
  api.confirmCalendarAgent.mockResolvedValue({});
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster: [{ ...roster[0], active: false, revision: 2 }], days: [], attendance: [] });
  await userEvent.click(screen.getByRole('button', { name: 'Confirmă în Magazin Alpha' }));
  await waitFor(() => expect(api.confirmCalendarAgent).toHaveBeenCalledWith('2026-09', 'AG1', { home_site_code: 'S1', active: false, expected_revision: 1 }));
  await waitFor(() => expect(screen.getByLabelText('Cod agent pentru confirmare')).toHaveValue(''));
  await userEvent.selectOptions(screen.getByLabelText('Cod agent pentru confirmare'), 'AG1');
  await userEvent.click(screen.getByLabelText('Activ în această lună'));
  await userEvent.click(screen.getByRole('button', { name: 'Confirmă în Magazin Alpha' }));
  await waitFor(() => expect(api.confirmCalendarAgent).toHaveBeenLastCalledWith('2026-09', 'AG1', { home_site_code: 'S1', active: true, expected_revision: 2 }));
});
it('closes the old day snapshot after a home-store correction', async () => {
  api.calendarStores.mockResolvedValue([store, { ...store, site_code: 'S2', locatie: 'Magazin Beta' }]);
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster: [{ ...roster[0], home_site_code: 'S2' }], days: [], attendance: [] });
  mount(); await openStore();
  await userEvent.click(screen.getByRole('button', { name: 'Editează 2026-09-01' }));
  await userEvent.selectOptions(screen.getByLabelText('Agent pentru zi'), 'AG1');
  await userEvent.click(screen.getByLabelText('Zi suplimentară plătită'));
  expect(screen.getByLabelText('Zi suplimentară plătită')).toBeChecked();
  await userEvent.click(screen.getByText('Confirmă agenții și magazinul de bază'));
  await userEvent.selectOptions(screen.getByLabelText('Cod agent pentru confirmare'), 'AG1');
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster: [{ ...roster[0], revision: 2 }], days: [], attendance: [] });
  api.confirmCalendarAgent.mockResolvedValue({});
  await userEvent.click(screen.getByRole('button', { name: 'Confirmă în Magazin Alpha' }));
  await waitFor(() => expect(screen.queryByLabelText('Agent pentru zi')).not.toBeInTheDocument());
  await waitFor(() => expect(screen.getByLabelText('Cod agent pentru confirmare')).toHaveValue(''));
  await userEvent.click(screen.getByRole('button', { name: 'Editează 2026-09-01' }));
  await userEvent.selectOptions(screen.getByLabelText('Agent pentru zi'), 'AG1');
  expect(screen.getByLabelText('Zi suplimentară plătită')).not.toBeChecked();
});
it('keeps unavailable scheduled stores accessible only for cancellation', async () => {
  api.calendarStores.mockResolvedValue([]);
  mount();
  await userEvent.click(await screen.findByRole('button', { name: /S1 · doar corectări/ }));
  expect(screen.getByText(/Magazin indisponibil pentru programări noi/)).toBeInTheDocument();
  expect(screen.queryByText('Confirmă agenții și magazinul de bază')).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Editează 2026-09-02' })).toBeDisabled();
  await userEvent.click(screen.getByRole('button', { name: 'Editează 2026-09-01' }));
  expect(screen.getByLabelText('Tip zi')).toHaveValue('cancelled');
  expect(screen.queryByRole('option', { name: 'Lucrează' })).not.toBeInTheDocument();
  api.saveCalendarDays.mockResolvedValue([]);
  await userEvent.click(screen.getByRole('button', { name: 'Salvează ziua' }));
  await waitFor(() => expect(api.saveCalendarDays).toHaveBeenCalledWith('2026-09', [{ agent_code: 'AG1', work_date: '2026-09-01', site_code: 'S1', status: 'cancelled', supplemental: false, expected_revision: 1 }]));
});
it('keeps date switching locked until a slow day save completes', async () => {
  let finish!: (value: unknown[]) => void;
  api.saveCalendarDays.mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  mount(); await openStore();
  await userEvent.click(screen.getByRole('button', { name: 'Editează 2026-09-01' }));
  await userEvent.click(screen.getByRole('button', { name: 'Salvează ziua' }));
  const otherDate = screen.getByRole('button', { name: 'Editează 2026-09-02' });
  expect(otherDate).toBeDisabled();
  await userEvent.click(otherDate);
  expect(screen.getByText('Program pentru 2026-09-01')).toBeInTheDocument();
  expect(api.saveCalendarDays).toHaveBeenCalledTimes(1);
  expect(screen.queryByText('Confirmă agenții și magazinul de bază')).not.toBeInTheDocument();
  finish([]);
  await waitFor(() => expect(otherDate).not.toBeDisabled());
  await userEvent.click(otherDate);
  expect(screen.getByText('Program pentru 2026-09-02')).toBeInTheDocument();
});
it('blocks day opening and saving until roster confirmation settles', async () => {
  let finish!: (value: object) => void;
  api.confirmCalendarAgent.mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  mount(); await openStore();
  await userEvent.click(screen.getByRole('button', { name: 'Editează 2026-09-01' }));
  await userEvent.click(screen.getByText('Confirmă agenții și magazinul de bază'));
  await userEvent.selectOptions(screen.getByLabelText('Cod agent pentru confirmare'), 'AG1');
  await userEvent.click(screen.getByRole('button', { name: 'Confirmă în Magazin Alpha' }));
  expect(screen.getByRole('button', { name: 'Editează 2026-09-02' })).toBeDisabled();
  expect(screen.getByRole('button', { name: 'Salvează ziua' })).toBeDisabled();
  await userEvent.click(screen.getByRole('button', { name: 'Salvează ziua' }));
  expect(api.saveCalendarDays).not.toHaveBeenCalled();
  finish({});
  await waitFor(() => expect(screen.getByRole('button', { name: 'Editează 2026-09-02' })).not.toBeDisabled());
  expect(screen.queryByLabelText('Agent pentru zi')).not.toBeInTheDocument();
});
it('saves monthly store hours with revision and reloads attendance', async () => {
  mount(); await openStore();
  await userEvent.click(screen.getByText(/Program magazin ·/));
  const { fireEvent } = await import('@testing-library/react');
  fireEvent.change(screen.getByLabelText('Deschidere'), { target: { value: '09:00' } });
  api.saveStoreHours.mockResolvedValue({ site_code: 'S1', opens: '09:00', closes: '22:00', break_minutes: 60, revision: 1 });
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster, days: [day], attendance: [], store_hours: [{ site_code: 'S1', opens: '09:00', closes: '22:00', break_minutes: 60, revision: 1 }], attendance_days: [{ ...day, worked_minutes: 720, opens: '09:00', closes: '22:00', break_minutes: 60 }], attendance_by_store: { S1: [{ agent_code: 'AG1', worked_minutes: 720 }] } });
  await userEvent.click(screen.getByRole('button', { name: 'Salvează programul magazinului' }));
  await waitFor(() => expect(api.saveStoreHours).toHaveBeenCalledWith('2026-09', 'S1', { opens: '09:00', closes: '22:00', break_minutes: 60, expected_revision: 0 }));
  expect(await screen.findByText(/Program magazin · 09:00/)).toBeInTheDocument();
  await userEvent.click(screen.getByRole('tab', { name: 'Pontaj' }));
  expect(screen.getByRole('table')).toHaveTextContent('09:00–22:00');
  expect(screen.getByRole('table')).toHaveTextContent('12');
});
it('downloads the displayed projection revision', async () => {
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster, days: [day], attendance: [], projection_revision: 'abc' });
  mount();
  await userEvent.click(await screen.findByRole('button', { name: 'Descarcă pontajele ZIP (provizoriu)' }));
  expect(api.downloadAttendance).toHaveBeenCalledWith('2026-09', 'abc');
});
it('keeps confirmed names and stable codes visible in the calendar and roster', async () => {
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster: [{ ...roster[0], display_name: 'Nume Confirmat', identity_status: 'confirmed' }], days: [day], attendance: [] });
  mount();
  await userEvent.click(await screen.findByRole('button', { name: /Magazin Alpha/ }));
  expect(screen.getByRole('button', { name: 'Editează 2026-09-01' })).toHaveTextContent('Nume Confirmat · AG1');
  await userEvent.click(screen.getByText('Confirmă agenții și magazinul de bază'));
  expect(screen.getByRole('option', { name: /Nume Confirmat · AG1/ })).toHaveValue('AG1');
});
it('filters managers, companies and stores without changing the monthly export scope', async () => {
  api.calendarStores.mockResolvedValue([store, { ...store, site_code: 'S2', locatie: 'Magazin Beta', firma: 'Other' }, { ...store, site_code: 'S3', locatie: 'Magazin Gamma', regional: 'Manager G' }, { ...store, site_code: 'S4', locatie: 'Magazin Delta', regional: '' }]);
  api.readCalendar.mockResolvedValue({ month: '2026-09', roster, days: [day], attendance: [], projection_revision: 'whole-month' });
  mount();
  await userEvent.selectOptions(await screen.findByLabelText('Manager program'), 'Manager R');
  expect(screen.getByRole('button', { name: /Magazin Alpha/ })).toBeVisible();
  expect(screen.queryByRole('button', { name: /Magazin Gamma/ })).not.toBeInTheDocument();
  await userEvent.selectOptions(screen.getByLabelText('Firmă program'), 'Other');
  expect(screen.queryByRole('button', { name: /Magazin Alpha/ })).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: /Magazin Beta/ })).toBeVisible();
  await userEvent.click(screen.getByRole('button', { name: 'Descarcă pontajele ZIP (provizoriu)' }));
  expect(api.downloadAttendance).toHaveBeenCalledWith('2026-09', 'whole-month');
  await userEvent.type(screen.getByLabelText('Caută magazin'), 'missing');
  expect(screen.getByText('Niciun magazin găsit')).toBeVisible();
  await userEvent.click(screen.getByRole('button', { name: 'Resetează filtrele' }));
  await userEvent.selectOptions(screen.getByLabelText('Manager program'), '__unassigned');
  expect(screen.getByRole('button', { name: /Magazin Delta/ })).toBeVisible();
  expect(api.saveCalendarDays).not.toHaveBeenCalled();
});
